import React from "react";
import "../../App.css";
import star from "../../assets/star.svg";
import {
  BallStyled,
  BoxBallsStyled,
  ContainerStyled,
  ImgStarStyled,
  StarsBoxStyled,
} from "./styles";

function DragonBall({ timeRotate }) {
  return (
    <ContainerStyled>
      <BoxBallsStyled timeRotate={timeRotate}>
        <BallStyled
          timeRotate={timeRotate}
          gridRow={1}
          gridColumn={2}
          justifySelf="flex-start"
        >
          <StarsBoxStyled>
            <ImgStarStyled src={star} alt="star" />
          </StarsBoxStyled>
        </BallStyled>
        <BallStyled
          gridRow={2}
          gridColumn={1}
          alignSelf="flex-start"
          justifySelf="center"
          timeRotate={timeRotate}
        >
          <StarsBoxStyled gridRow={2} gridColumn={2}>
            <ImgStarStyled src={star} alt="star" margin={5} />
            <ImgStarStyled src={star} alt="star" margin={5} />
          </StarsBoxStyled>
        </BallStyled>
        <BallStyled
          gridRow={2}
          gridColumn={3}
          alignSelf="flex-start"
          justifySelf="center"
          timeRotate={timeRotate}
        >
          <StarsBoxStyled stars={3}>
            <ImgStarStyled
              src={star}
              alt="star"
              alignSelf="center"
              justifySelf="flex-end"
            />
            <ImgStarStyled
              src={star}
              alt="star"
              alignSelf="flex-end"
              justifySelf="center"
            />
            <ImgStarStyled
              src={star}
              alt="star"
              alignSelf="center"
              justifySelf="flex-end"
            />
          </StarsBoxStyled>
        </BallStyled>
        <BallStyled
          gridRow={3}
          gridColumn={1}
          alignSelf="flex-end"
          justifySelf="center"
          timeRotate={timeRotate}
        >
          <StarsBoxStyled stars={4}>
            <ImgStarStyled
              src={star}
              alt="star"
              alignSelf="center"
              justifySelf="center"
            />
            <ImgStarStyled
              src={star}
              alt="star"
              alignSelf="center"
              justifySelf="center"
            />
            <ImgStarStyled
              src={star}
              alt="star"
              alignSelf="center"
              justifySelf="center"
            />
            <ImgStarStyled
              src={star}
              alt="star"
              alignSelf="center"
              justifySelf="center"
            />
          </StarsBoxStyled>
        </BallStyled>
        <BallStyled
          gridRow={3}
          gridColumn={3}
          alignSelf="flex-end"
          justifySelf="center"
          timeRotate={timeRotate}
        >
          <StarsBoxStyled stars={5}>
            <ImgStarStyled
              src={star}
              alt="star"
              alignSelf="flex-end"
              justifySelf="center"
            />
            <ImgStarStyled
              src={star}
              alt="star"
              alignSelf="flex-end"
              justifySelf="center"
            />
            <ImgStarStyled
              src={star}
              alt="star"
              alignSelf="center"
              justifySelf="center"
              gridRowStart={2}
              gridColumnStart={1}
              gridRowEnd={2}
              gridColumnEnd={3}
            />
            <ImgStarStyled
              src={star}
              alt="star"
              alignSelf="flex-start"
              justifySelf="center"
            />
            <ImgStarStyled
              src={star}
              alt="star"
              alignSelf="flex-start"
              justifySelf="center"
            />
          </StarsBoxStyled>
        </BallStyled>
        <BallStyled
          timeRotate={timeRotate}
          gridRow={4}
          gridColumn={2}
          justifySelf="flex-start"
        >
          <StarsBoxStyled stars={6}>
            <ImgStarStyled
              src={star}
              alt="star"
              alignSelf="flex-end"
              justifySelf="center"
              gridRowStart={1}
              gridColumnStart={1}
              gridRowEnd={1}
              gridColumnEnd={3}
            />
            <ImgStarStyled
              src={star}
              alt="star"
              alignSelf="flex-start"
              justifySelf="center"
              gridRowStart={2}
              gridColumnStart={1}
              gridRowEnd={3}
              gridColumnEnd={2}
            />
            <ImgStarStyled
              src={star}
              alt="star"
              alignSelf="center"
              justifySelf="center"
              gridRowStart={2}
              gridColumnStart={1}
              gridRowEnd={4}
              gridColumnEnd={3}
            />

            <ImgStarStyled
              src={star}
              alt="star"
              alignSelf="flex-start"
              justifySelf="center"
              gridRowStart={2}
              gridColumnStart={2}
              gridRowEnd={2}
              gridColumnEnd={3}
            />

            <ImgStarStyled
              src={star}
              alt="star"
              alignSelf="flex-end"
              justifySelf="center"
              gridRowStart={3}
              gridColumnStart={1}
              gridRowEnd={3}
              gridColumnEnd={1}
            />
            <ImgStarStyled
              src={star}
              alt="star"
              alignSelf="center"
              justifySelf="center"
              gridRowStart={3}
              gridColumnStart={2}
              gridRowEnd={3}
              gridColumnEnd={3}
            />
          </StarsBoxStyled>
        </BallStyled>
      </BoxBallsStyled>
      <BallStyled timeRotate={timeRotate} position>
        <StarsBoxStyled stars={6} timeRotate={timeRotate}>
          <ImgStarStyled
            src={star}
            alt="star"
            alignSelf="flex-end"
            justifySelf="center"
            gridRowStart={1}
            gridColumnStart={1}
            gridRowEnd={1}
            gridColumnEnd={3}
          />
          <ImgStarStyled
            src={star}
            alt="star"
            alignSelf="flex-start"
            justifySelf="center"
            gridRowStart={2}
            gridColumnStart={1}
            gridRowEnd={3}
            gridColumnEnd={2}
          />
          <ImgStarStyled
            src={star}
            alt="star"
            alignSelf="center"
            justifySelf="center"
            gridRowStart={2}
            gridColumnStart={1}
            gridRowEnd={4}
            gridColumnEnd={3}
          />

          <ImgStarStyled
            src={star}
            alt="star"
            alignSelf="flex-start"
            justifySelf="center"
            gridRowStart={2}
            gridColumnStart={2}
            gridRowEnd={2}
            gridColumnEnd={3}
          />

          <ImgStarStyled
            src={star}
            alt="star"
            alignSelf="flex-end"
            justifySelf="center"
            gridRowStart={3}
            gridColumnStart={1}
            gridRowEnd={3}
            gridColumnEnd={1}
          />
          <ImgStarStyled
            src={star}
            alt="star"
            alignSelf="center"
            justifySelf="center"
            gridRowStart={3}
            gridColumnStart={2}
            gridRowEnd={3}
            gridColumnEnd={3}
          />
          <ImgStarStyled
            src={star}
            alt="star"
            alignSelf="flex-start"
            justifySelf="center"
            gridRowStart={4}
            gridColumnStart={1}
            gridRowEnd={5}
            gridColumnEnd={3}
          />
        </StarsBoxStyled>
      </BallStyled>
    </ContainerStyled>
  );
}

export default DragonBall;
